import type { Event } from './types';

export const EVENTS: Event[] = [
  {
    id: "2024-singapore-liquidstaking",
    name: "Liquid Staking Night with aPriori, Infrared & Lorenzo Protocol",
    location: "Singapore, Singapore",
    venue: "",
    lat: 1.3521,
    lng: 103.8198,
    startDate: "2024-09-17",
    endDate: "2024-09-17",
    emoji: "🍸",
    icon: "",
    color: "#4f9eff",
    description:
      "Enjoy an evening of drinks and food with 3 top Liquid Staking Protocols across Monad, Berachain, and Babylon. All backed by Binance Labs.",
    stats: [
      { value: "239", label: "Attendees" },
      { value: "3",   label: "Protocols" },
      { value: "1",   label: "Night" },
      { value: "∞",   label: "Vibes" },
    ],
    photos: [
      "/assets/LiquidStakingNight",
      "",
      "",
      "",
    ],
    merch: [],
    links: [
      { label: "Event Page", url: "https://luma.com/u7p1vn54", icon: "🌐" },
    ],
  },

  {
    id: "2024-singapore-beracup",
    name: "Beracup @ Token2049",
    location: "Singapore, Singapore",
    venue: "OCBC Arena",
    lat: 1.3048,
    lng: 103.8748,
    startDate: "2024-09-20",
    endDate: "2024-09-20",
    emoji: "🏀",
    icon: "",
    color: "#f97316",
    description:
      "An energetic basketball tournament bringing together the Berachain community during Token2049. Featuring competitive 5v5 games, open courts, and exclusive merch drops.",
    stats: [
      { value: "189", label: "Attendees" },
      { value: "3",   label: "Courts" },
      { value: "2",   label: "Game Modes" },
      { value: "1",   label: "Cup" },
    ],
    photos: [
      "/assets/BeracupBasketball",
      "",
      "",
      "",
    ],
    merch: [],
    links: [
      { label: "Event Page", url: "https://lu.ma/3k0ddwwu", icon: "🌐" },
    ],
  },

  {
    id: "2024-bangkok-beracup",
    name: "Beracup @ Devcon",
    location: "Bangkok, Thailand",
    venue: "Basketball B Pro",
    lat: 13.7563,
    lng: 100.5018,
    startDate: "2024-11-11",
    endDate: "2024-11-11",
    emoji: "🏀",
    icon: "",
    color: "#a855f7",
    description:
      "A high-energy basketball tournament during Devcon featuring competitive games, free play courts, and skill contests with exclusive Berachain ecosystem prizes.",
    stats: [
      { value: "787", label: "Attendees" },
      { value: "3",   label: "Courts" },
      { value: "5v5", label: "Format" },
      { value: "∞",   label: "Energy" },
    ],
    photos: [
      "/assets/BeracupDevcon",
      "",
      "",
      "",
    ],
    merch: [],
    links: [
      { label: "Event Page", url: "https://lu.ma/beracup", icon: "🌐" },
    ],
  },

  {
    id: "2024-bangkok-hotpotdao",
    name: "HotpotDAO - Devcon Thailand 2024",
    location: "Bangkok, Thailand",
    venue: "Shoo Loong Kan Hotpot",
    lat: 13.7563,
    lng: 100.5018,
    startDate: "2024-11-12",
    endDate: "2024-11-12",
    emoji: "🍲",
    icon: "",
    color: "#22c55e",
    description:
      "A curated Devcon evening bringing together founders, capital allocators, and operators over hotpot, conversation, and networking.",
    stats: [
      { value: "601",  label: "Attendees" },
      { value: "10+",  label: "Teams" },
      { value: "1",    label: "Night" },
      { value: "🍲",   label: "Hotpot" },
    ],
    photos: [
      "/assets/HotpotDao",
      "",
      "",
      "",
    ],
    merch: [],
    links: [
      { label: "Event Page", url: "https://lu.ma/mmrgk0hj?tk=5VSvY0", icon: "🌐" },
    ],
  },

  {
    id: "2024-bangkok-beraspa",
    name: "Bera Spa '24",
    location: "Bangkok, Thailand",
    venue: "Infinity Wellbeing",
    lat: 13.7563,
    lng: 100.5018,
    startDate: "2024-11-13",
    endDate: "2024-11-13",
    emoji: "💆‍♀️",
    icon: "",
    color: "#06b6d4",
    description:
      "A relaxing Devcon-side experience featuring massages, networking, and conversations with Infrared, Exponents, and Zellic.",
    stats: [
      { value: "171",   label: "Attendees" },
      { value: "30min", label: "Sessions" },
      { value: "3",     label: "Teams" },
      { value: "♨️",    label: "Relaxation" },
    ],
    photos: [
      "/assets/BeraSpa1",
      "/assets/Beraspa3",
      "",
      "",
    ],
    merch: [],
    links: [
      { label: "Event Page", url: "https://lu.ma/8u1lrecl", icon: "🌐" },
    ],
  },

  {
    id: "2024-bangkok-honeyhour",
    name: "Honey Hour",
    location: "Bangkok, Thailand",
    venue: "Amber Bar.BKK",
    lat: 13.7563,
    lng: 100.5018,
    startDate: "2024-11-13",
    endDate: "2024-11-13",
    emoji: "🍯",
    icon: "",
    color: "#f59e0b",
    description:
      "A relaxed Devcon-side gathering with drinks, networking, and Berachain ecosystem vibes just steps away from the conference.",
    stats: [
      { value: "363", label: "Attendees" },
      { value: "4",   label: "Projects" },
      { value: "1",   label: "Night" },
      { value: "🍯",  label: "Honey" },
    ],
    photos: ["/assets/HoneyHour", "", "", ""],
    merch: [],
    links: [
      { label: "Event Page", url: "https://luma.com/honeyhour?tk=vQ2xxh", icon: "🌐" },
    ],
  },

  {
    id: "2024-denver-honeyhappyhour",
    name: "Honey Happy Hour",
    location: "Denver, United States",
    venue: "Tom's Watch Bar - Coors Field",
    lat: 39.7392,
    lng: -104.9903,
    startDate: "2025-02-25",
    endDate: "2025-02-25",
    emoji: "🍯",
    icon: "",
    color: "#eab308",
    description:
      "A pre-ETH Denver networking event featuring drinks, games, and a Berachain-focused panel on Proof of Liquidity and ecosystem growth.",
    stats: [
      { value: "470", label: "Attendees" },
      { value: "1",   label: "Panel" },
      { value: "5+",  label: "Projects" },
      { value: "🍹",  label: "Drinks" },
    ],
    photos: ["/assets/HoneyHappyHour", "", "", ""],
    merch: [],
    links: [
      { label: "Event Page", url: "https://luma.com/pf4uuzzz", icon: "🌐" },
    ],
  },

  {
    id: "2024-taipei-infrared101",
    name: "Infrared 101: Unlocking DeFi on Berachain",
    location: "Taipei, Taiwan",
    venue: "Cozy Cowork Cafe",
    lat: 25.0330,
    lng: 121.5654,
    startDate: "2024-12-15",
    endDate: "2024-12-15",
    emoji: "📚",
    icon: "",
    color: "#6366f1",
    description:
      "An educational workshop introducing Infrared Finance and Berachain's Proof of Liquidity through talks, games, and interactive learning.",
    stats: [
      { value: "210", label: "Attendees" },
      { value: "1",   label: "Workshop" },
      { value: "🎯",  label: "Learning" },
      { value: "🎁",  label: "Rewards" },
    ],
    photos: ["/assets/Infrared101", "", "", ""],
    merch: [],
    links: [
      { label: "Event Page", url: "https://luma.com/hgp7hvse", icon: "🌐" },
    ],
  },

  {
    id: "2024-denver-infraredbowl",
    name: "Let's Bowl: Drinks & Networking",
    location: "Denver, United States",
    venue: "Lucky Strike Denver",
    lat: 39.7392,
    lng: -104.9903,
    startDate: "2025-02-28",
    endDate: "2025-02-28",
    emoji: "🎳",
    icon: "",
    color: "#ef4444",
    description:
      "A bowling and networking event during ETH Denver featuring games, drinks, and community building with Infrared and partners.",
    stats: [
      { value: "338", label: "Attendees" },
      { value: "🎳",  label: "Bowling" },
      { value: "🍻",  label: "Drinks" },
      { value: "🎱",  label: "Games" },
    ],
    photos: ["/assets/InfraredBowl", "", "", ""],
    merch: [],
    links: [
      { label: "Event Page", url: "https://luma.com/k2hytu51", icon: "🌐" },
    ],
  },

  {
    id: "2024-denver-allin",
    name: "ALL-INnovation | Founders & VIP Soirée",
    location: "Denver, United States",
    venue: "Mirus Gallery & Art Bar",
    lat: 39.7392,
    lng: -104.9903,
    startDate: "2025-02-28",
    endDate: "2025-02-28",
    emoji: "♠️",
    icon: "",
    color: "#8b5cf6",
    description:
      "An exclusive founders-only soirée blending networking, games, and nightlife with curated experiences, competitions, and VIP access.",
    stats: [
      { value: "209", label: "Attendees" },
      { value: "VIP", label: "Access" },
      { value: "♠️",  label: "Poker" },
      { value: "🎧",  label: "Afterparty" },
    ],
    photos: ["/assets/InfraredAllIn", "/assets/AllinLounge", "", ""],
    merch: [],
    links: [],
  },

  {
    id: "2024-taipei-mrblock",
    name: "MrBlock Summit 2024",
    location: "Taipei, Taiwan",
    venue: "Syntrend Creative Park",
    lat: 25.0330,
    lng: 121.5654,
    startDate: "2024-12-12",
    endDate: "2024-12-12",
    emoji: "🏛️",
    icon: "",
    color: "#14b8a6",
    description:
      "A major blockchain summit featuring industry leaders, panels, and project presentations exploring the future of crypto, DeFi, and infrastructure.",
    stats: [
      { value: "1 Day",  label: "Summit" },
      { value: "20+",    label: "Speakers" },
      { value: "Panels", label: "Content" },
      { value: "Global", label: "Audience" },
    ],
    photos: ["/assets/MrBlock2024", "", "", ""],
    merch: [],
    links: [
      { label: "Event Page", url: "https://luma.com/mrblock_summit_2024", icon: "🌐" },
    ],
  },

  {
    id: "2025-taipei-mrblock",
    name: "MrBlock Summit 2025",
    location: "Taipei, Taiwan",
    venue: "Syntrend Creative Park",
    lat: 25.0330,
    lng: 121.5654,
    startDate: "2025-09-05",
    endDate: "2025-09-05",
    emoji: "🚀",
    icon: "",
    color: "#0ea5e9",
    description:
      "The flagship MrBlock summit bringing together top blockchain projects, investors, and communities to explore emerging trends like DeFi 2.0, LRTs, and rollups.",
    stats: [
      { value: "763",    label: "Attendees" },
      { value: "Global", label: "Projects" },
      { value: "1",      label: "Day" },
      { value: "🚀",     label: "Innovation" },
    ],
    photos: ["/assets/MrBlock2025", "", "", ""],
    merch: [],
    links: [
      { label: "Event Page", url: "https://luma.com/mrblock_tpe_2025?tk=pgUsiB", icon: "🌐" },
    ],
  },

  {
    id: "2024-hongkong-honeyhour",
    name: "Liquid Honey Hour",
    location: "Hong Kong, Hong Kong",
    venue: "AOAO",
    lat: 22.3193,
    lng: 114.1694,
    startDate: "2025-04-09",
    endDate: "2025-04-09",
    emoji: "🍯",
    icon: "",
    color: "#f59e0b",
    description:
      "A Hong Kong gathering for the Berachain ecosystem featuring drinks, networking, and conversations with Infrared, Deek Network, and Auros.",
    stats: [
      { value: "201", label: "Attendees" },
      { value: "3",   label: "Projects" },
      { value: "1",   label: "Night" },
      { value: "🍯",  label: "Honey" },
    ],
    photos: ["/assets/HKHappyHour", "", "", ""],
    merch: [],
    links: [
      { label: "Event Page", url: "https://luma.com/mr5s7z88", icon: "🌐" },
    ],
  },

  {
    id: "2024-seoul-beras",
    name: "Beras in Seoul: On-Chain Kimistri",
    location: "Seoul, South Korea",
    venue: "Kemistri Seoul",
    lat: 37.5665,
    lng: 126.9780,
    startDate: "2025-04-16",
    endDate: "2025-04-16",
    emoji: "🧪",
    icon: "",
    color: "#ec4899",
    description:
      "An invite-only Seoul mixer bringing together Berachain builders, founders, and community members for networking and collaboration.",
    stats: [
      { value: "277",    label: "Attendees" },
      { value: "5",      label: "Partners" },
      { value: "Invite", label: "Only" },
      { value: "🧪",     label: "Chemistry" },
    ],
    photos: ["/assets/BerasInSeoul", "", "", ""],
    merch: [],
    links: [
      { label: "Event Page", url: "https://luma.com/sevs1qmx", icon: "🌐" },
    ],
  },

  {
    id: "2024-dubai-honeyhour",
    name: "Beras Honey Hour with Magna & Infrared",
    location: "Dubai, United Arab Emirates",
    venue: "Brass Monkey - Bluewaters",
    lat: 25.2048,
    lng: 55.2708,
    startDate: "2025-05-02",
    endDate: "2025-05-02",
    emoji: "🍯",
    icon: "",
    color: "#facc15",
    description:
      "A late-night Token2049 Dubai gathering featuring networking, drinks, bowling, and discussions around Berachain and Proof of Liquidity.",
    stats: [
      { value: "270", label: "Attendees" },
      { value: "2",   label: "Hosts" },
      { value: "🌙",  label: "Night" },
      { value: "🎳",  label: "Bowling" },
    ],
    photos: ["/assets/HoneyHourMagna", "", "", ""],
    merch: [],
    links: [
      { label: "Event Page", url: "https://luma.com/n8rg3ymo", icon: "🌐" },
    ],
  },

  {
    id: "2024-seoul-kbw",
    name: "KBW Shuttle Bus by Infrared x Lair",
    location: "Seoul, South Korea",
    venue: "Walkerhill Hotels & Resorts",
    lat: 37.5665,
    lng: 126.9780,
    startDate: "2025-09-23",
    endDate: "2025-09-24",
    emoji: "🚌",
    icon: "",
    color: "#0ea5e9",
    description:
      "Official KBW shuttle service connecting key locations across Seoul, designed to help attendees move seamlessly between events while networking with the community.",
    stats: [
      { value: "894", label: "Riders" },
      { value: "2",   label: "Days" },
      { value: "🚌",  label: "Shuttles" },
      { value: "🎁",  label: "Swag" },
    ],
    photos: ["/assets/KBWShuttle", "", "", ""],
    merch: [],
    links: [
      { label: "Event Page", url: "https://luma.com/38wpurid", icon: "🌐" },
    ],
  },
];
